name: EasySpawn
main: net.jimmy1248.easyspawn.EasySpawn
version: 1.7.5-R0.1
commands:
  spawn:
    description: Teleports you to spawn
    usage: /spawn
    permission: easyspawn.spawn
    permission-message: You don't have <permission>
  bed:
    description: Teleports you to your bed
    usage: /bed
    permission: easyspawn.bed
    permission-message: You don't have <permission>
  setspawn:
    description: Sets spawn location
    usage: /setspawn
    permission: easyspawn.setspawn
    permission-message: You don't have <permission>
permissions:
  easyspawn.spawn:
    description: Teleports you to spawn
    default: true
  easyspawn.bed:
    description: Teleports you to your bed
    default: true
  easyspawn.setspawn:
    description: Sets spawn location
    default: op
